/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UpgradeArgs = IDL.Record({
	rate_per_gb_per_month: IDL.Opt(IDL.Nat64),
	admins: IDL.Opt(IDL.Vec(IDL.Principal)),
	shared_secret: IDL.Opt(IDL.Vec(IDL.Nat8))
});
export const InitArgs = IDL.Record({
	rate_per_gb_per_month: IDL.Nat64,
	admins: IDL.Vec(IDL.Principal),
	shared_secret: IDL.Vec(IDL.Nat8)
});
export const Args = IDL.Variant({
	Upgrade: IDL.Opt(UpgradeArgs),
	Init: InitArgs
});
export const DirectoryError = IDL.Variant({
	AccountExpired: IDL.Null,
	UploadSessionNotFound: IDL.Null,
	AdminOnly: IDL.Null,
	PaymentFailed: IDL.Text,
	Unauthorized: IDL.Null,
	LinkNotFound: IDL.Null,
	FileNotFound: IDL.Null,
	LinkExpired: IDL.Null,
	InvalidRequest: IDL.Text,
	NoWritableBuckets: IDL.Null,
	TransferFailed: IDL.Text,
	UploadIncomplete: IDL.Record({
		expected: IDL.Nat32,
		uploaded: IDL.Nat32
	}),
	QuotaExceeded: IDL.Record({
		requested: IDL.Nat64,
		used: IDL.Nat64,
		quota: IDL.Nat64
	})
});
export const AbortUploadResult = IDL.Variant({
	Ok: IDL.Null,
	Err: DirectoryError
});
export const FileId = IDL.Record({
	id: IDL.Vec(IDL.Nat8),
	owner: IDL.Principal
});
export const FileRole = IDL.Variant({
	Reader: IDL.Null,
	Writer: IDL.Null
});
export const FileStatus = IDL.Variant({
	Ready: IDL.Null,
	Deleted: IDL.Null,
	Pending: IDL.Null
});
export const FileMeta = IDL.Record({
	readers: IDL.Vec(IDL.Principal),
	status: FileStatus,
	sha256: IDL.Opt(IDL.Vec(IDL.Nat8)),
	mime: IDL.Text,
	name: IDL.Text,
	size_bytes: IDL.Nat64,
	updated_at_ns: IDL.Nat64,
	created_at_ns: IDL.Nat64,
	chunk_count: IDL.Nat32,
	writers: IDL.Vec(IDL.Principal),
	chunk_size: IDL.Nat32,
	file_id: FileId
});
export const CommitUploadResult = IDL.Variant({
	Ok: FileMeta,
	Err: DirectoryError
});
export const CreateShareLinkResult = IDL.Variant({
	Ok: IDL.Vec(IDL.Nat8),
	Err: DirectoryError
});
export const DeleteFileResult = IDL.Variant({
	Ok: IDL.Null,
	Err: DirectoryError
});
export const Account = IDL.Record({
	owner: IDL.Principal,
	subaccount: IDL.Opt(IDL.Vec(IDL.Nat8))
});
export const PatronPaysIcrc2Tokens = IDL.Record({
	ledger: IDL.Principal,
	patron: Account
});
export const CallerPaysIcrc2Tokens = IDL.Record({ ledger: IDL.Principal });
export const PaymentType = IDL.Variant({
	PatronPaysIcrc2Tokens: PatronPaysIcrc2Tokens,
	AttachedCycles: IDL.Null,
	CallerPaysIcrc2Cycles: IDL.Null,
	CallerPaysIcrc2Tokens: CallerPaysIcrc2Tokens,
	PatronPaysIcrc2Cycles: Account
});
export const DownloadToken = IDL.Record({
	sig: IDL.Vec(IDL.Nat8),
	bucket_id: IDL.Principal,
	directory_id: IDL.Principal,
	expires_at: IDL.Nat64,
	file_id: FileId
});
export const BucketAuth = IDL.Record({
	token: DownloadToken,
	bucket_id: IDL.Principal
});
export const ChunkLocation = IDL.Record({
	chunk_index: IDL.Nat32,
	bucket: IDL.Principal
});
export const DownloadPlan = IDL.Record({
	auth: IDL.Vec(BucketAuth),
	chunk_count: IDL.Nat32,
	locations: IDL.Vec(ChunkLocation),
	chunk_size: IDL.Nat32
});
export const GetDownloadPlanResult = IDL.Variant({
	Ok: DownloadPlan,
	Err: DirectoryError
});
export const GetFileMetaResult = IDL.Variant({
	Ok: FileMeta,
	Err: DirectoryError
});
export const PricingConfig = IDL.Record({
	rate_per_gb_per_month: IDL.Nat64
});
export const CanisterStatus = IDL.Record({
	cycles_balance: IDL.Nat,
	memory_usage_bytes: IDL.Nat64,
	version: IDL.Text,
	heap_memory_usage_bytes: IDL.Nat64
});
export const UploadToken = IDL.Record({
	sig: IDL.Vec(IDL.Nat8),
	bucket_id: IDL.Principal,
	upload_id: IDL.Vec(IDL.Nat8),
	directory_id: IDL.Principal,
	expires_at: IDL.Nat64,
	allowed_chunks: IDL.Vec(IDL.Nat32),
	file_id: FileId
});
export const GetUploadTokensResult = IDL.Variant({
	Ok: IDL.Vec(UploadToken),
	Err: DirectoryError
});
export const UserState = IDL.Record({
	used_bytes: IDL.Nat64,
	prepaid_balance: IDL.Nat64,
	quota_bytes: IDL.Nat64,
	expires_at_ns: IDL.Opt(IDL.Nat64)
});
export const UploadSession = IDL.Record({
	expected_chunk_count: IDL.Nat32,
	mime: IDL.Text,
	name: IDL.Text,
	upload_id: IDL.Vec(IDL.Nat8),
	expected_size_bytes: IDL.Nat64,
	chunk_size: IDL.Nat32,
	uploaded_chunks: IDL.Vec(IDL.Nat32),
	expires_at_ns: IDL.Nat64,
	file_id: FileId
});
export const StartUploadResult = IDL.Variant({
	Ok: UploadSession,
	Err: DirectoryError
});
export const TopUpBalanceResult = IDL.Variant({
	Ok: IDL.Nat64,
	Err: DirectoryError
});

export const idlService = IDL.Service({
	abort_upload: IDL.Func([IDL.Vec(IDL.Nat8)], [AbortUploadResult], []),
	add_file_access: IDL.Func([FileId, IDL.Principal, FileRole], [AbortUploadResult], []),
	admin_set_pricing: IDL.Func([IDL.Nat64], [AbortUploadResult], []),
	admin_set_quota: IDL.Func([IDL.Principal, IDL.Nat64], [AbortUploadResult], []),
	admin_withdraw: IDL.Func([IDL.Principal, IDL.Nat64, IDL.Principal], [AbortUploadResult], []),
	commit_upload: IDL.Func([IDL.Vec(IDL.Nat8)], [CommitUploadResult], []),
	create_share_link: IDL.Func([FileId, IDL.Nat64], [CreateShareLinkResult], []),
	delete_file: IDL.Func([FileId], [DeleteFileResult], []),
	estimate_upload_cost: IDL.Func([IDL.Nat64, PaymentType], [IDL.Nat64], ['query']),
	garbage_collect: IDL.Func([], [], []),
	get_download_plan: IDL.Func([FileId], [GetDownloadPlanResult], ['query']),
	get_file_meta: IDL.Func([FileId], [GetFileMetaResult], ['query']),
	get_pricing: IDL.Func([], [PricingConfig], ['query']),
	get_status: IDL.Func([], [CanisterStatus], ['query']),
	get_upload_tokens: IDL.Func([IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat32)], [GetUploadTokensResult], []),
	get_usage: IDL.Func([IDL.Opt(IDL.Principal)], [UserState], ['query']),
	list_files: IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
	provision_bucket: IDL.Func([IDL.Principal], [DeleteFileResult], []),
	reap_expired_uploads: IDL.Func([], [], []),
	remove_file_access: IDL.Func([FileId, IDL.Principal], [DeleteFileResult], []),
	report_chunk_uploaded: IDL.Func([IDL.Vec(IDL.Nat8), IDL.Nat32], [DeleteFileResult], []),
	resolve_share_link: IDL.Func([IDL.Vec(IDL.Nat8)], [GetDownloadPlanResult], ['query']),
	revoke_share_link: IDL.Func([IDL.Vec(IDL.Nat8)], [DeleteFileResult], []),
	start_upload: IDL.Func(
		[IDL.Text, IDL.Text, IDL.Nat64, IDL.Opt(PaymentType)],
		[StartUploadResult],
		[]
	),
	top_up_balance: IDL.Func([IDL.Nat64, PaymentType], [TopUpBalanceResult], [])
});

export const idlInitArgs = [Args];

export const idlFactory = ({ IDL }) => {
	const UpgradeArgs = IDL.Record({
		rate_per_gb_per_month: IDL.Opt(IDL.Nat64),
		admins: IDL.Opt(IDL.Vec(IDL.Principal)),
		shared_secret: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const InitArgs = IDL.Record({
		rate_per_gb_per_month: IDL.Nat64,
		admins: IDL.Vec(IDL.Principal),
		shared_secret: IDL.Vec(IDL.Nat8)
	});
	const Args = IDL.Variant({
		Upgrade: IDL.Opt(UpgradeArgs),
		Init: InitArgs
	});
	const DirectoryError = IDL.Variant({
		AccountExpired: IDL.Null,
		UploadSessionNotFound: IDL.Null,
		AdminOnly: IDL.Null,
		PaymentFailed: IDL.Text,
		Unauthorized: IDL.Null,
		LinkNotFound: IDL.Null,
		FileNotFound: IDL.Null,
		LinkExpired: IDL.Null,
		InvalidRequest: IDL.Text,
		NoWritableBuckets: IDL.Null,
		TransferFailed: IDL.Text,
		UploadIncomplete: IDL.Record({
			expected: IDL.Nat32,
			uploaded: IDL.Nat32
		}),
		QuotaExceeded: IDL.Record({
			requested: IDL.Nat64,
			used: IDL.Nat64,
			quota: IDL.Nat64
		})
	});
	const AbortUploadResult = IDL.Variant({
		Ok: IDL.Null,
		Err: DirectoryError
	});
	const FileId = IDL.Record({
		id: IDL.Vec(IDL.Nat8),
		owner: IDL.Principal
	});
	const FileRole = IDL.Variant({ Reader: IDL.Null, Writer: IDL.Null });
	const FileStatus = IDL.Variant({
		Ready: IDL.Null,
		Deleted: IDL.Null,
		Pending: IDL.Null
	});
	const FileMeta = IDL.Record({
		readers: IDL.Vec(IDL.Principal),
		status: FileStatus,
		sha256: IDL.Opt(IDL.Vec(IDL.Nat8)),
		mime: IDL.Text,
		name: IDL.Text,
		size_bytes: IDL.Nat64,
		updated_at_ns: IDL.Nat64,
		created_at_ns: IDL.Nat64,
		chunk_count: IDL.Nat32,
		writers: IDL.Vec(IDL.Principal),
		chunk_size: IDL.Nat32,
		file_id: FileId
	});
	const CommitUploadResult = IDL.Variant({
		Ok: FileMeta,
		Err: DirectoryError
	});
	const CreateShareLinkResult = IDL.Variant({
		Ok: IDL.Vec(IDL.Nat8),
		Err: DirectoryError
	});
	const DeleteFileResult = IDL.Variant({
		Ok: IDL.Null,
		Err: DirectoryError
	});
	const Account = IDL.Record({
		owner: IDL.Principal,
		subaccount: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const PatronPaysIcrc2Tokens = IDL.Record({
		ledger: IDL.Principal,
		patron: Account
	});
	const CallerPaysIcrc2Tokens = IDL.Record({ ledger: IDL.Principal });
	const PaymentType = IDL.Variant({
		PatronPaysIcrc2Tokens: PatronPaysIcrc2Tokens,
		AttachedCycles: IDL.Null,
		CallerPaysIcrc2Cycles: IDL.Null,
		CallerPaysIcrc2Tokens: CallerPaysIcrc2Tokens,
		PatronPaysIcrc2Cycles: Account
	});
	const DownloadToken = IDL.Record({
		sig: IDL.Vec(IDL.Nat8),
		bucket_id: IDL.Principal,
		directory_id: IDL.Principal,
		expires_at: IDL.Nat64,
		file_id: FileId
	});
	const BucketAuth = IDL.Record({
		token: DownloadToken,
		bucket_id: IDL.Principal
	});
	const ChunkLocation = IDL.Record({
		chunk_index: IDL.Nat32,
		bucket: IDL.Principal
	});
	const DownloadPlan = IDL.Record({
		auth: IDL.Vec(BucketAuth),
		chunk_count: IDL.Nat32,
		locations: IDL.Vec(ChunkLocation),
		chunk_size: IDL.Nat32
	});
	const GetDownloadPlanResult = IDL.Variant({
		Ok: DownloadPlan,
		Err: DirectoryError
	});
	const GetFileMetaResult = IDL.Variant({
		Ok: FileMeta,
		Err: DirectoryError
	});
	const PricingConfig = IDL.Record({ rate_per_gb_per_month: IDL.Nat64 });
	const CanisterStatus = IDL.Record({
		cycles_balance: IDL.Nat,
		memory_usage_bytes: IDL.Nat64,
		version: IDL.Text,
		heap_memory_usage_bytes: IDL.Nat64
	});
	const UploadToken = IDL.Record({
		sig: IDL.Vec(IDL.Nat8),
		bucket_id: IDL.Principal,
		upload_id: IDL.Vec(IDL.Nat8),
		directory_id: IDL.Principal,
		expires_at: IDL.Nat64,
		allowed_chunks: IDL.Vec(IDL.Nat32),
		file_id: FileId
	});
	const GetUploadTokensResult = IDL.Variant({
		Ok: IDL.Vec(UploadToken),
		Err: DirectoryError
	});
	const UserState = IDL.Record({
		used_bytes: IDL.Nat64,
		prepaid_balance: IDL.Nat64,
		quota_bytes: IDL.Nat64,
		expires_at_ns: IDL.Opt(IDL.Nat64)
	});
	const UploadSession = IDL.Record({
		expected_chunk_count: IDL.Nat32,
		mime: IDL.Text,
		name: IDL.Text,
		upload_id: IDL.Vec(IDL.Nat8),
		expected_size_bytes: IDL.Nat64,
		chunk_size: IDL.Nat32,
		uploaded_chunks: IDL.Vec(IDL.Nat32),
		expires_at_ns: IDL.Nat64,
		file_id: FileId
	});
	const StartUploadResult = IDL.Variant({
		Ok: UploadSession,
		Err: DirectoryError
	});
	const TopUpBalanceResult = IDL.Variant({
		Ok: IDL.Nat64,
		Err: DirectoryError
	});

	return IDL.Service({
		abort_upload: IDL.Func([IDL.Vec(IDL.Nat8)], [AbortUploadResult], []),
		add_file_access: IDL.Func([FileId, IDL.Principal, FileRole], [AbortUploadResult], []),
		admin_set_pricing: IDL.Func([IDL.Nat64], [AbortUploadResult], []),
		admin_set_quota: IDL.Func([IDL.Principal, IDL.Nat64], [AbortUploadResult], []),
		admin_withdraw: IDL.Func([IDL.Principal, IDL.Nat64, IDL.Principal], [AbortUploadResult], []),
		commit_upload: IDL.Func([IDL.Vec(IDL.Nat8)], [CommitUploadResult], []),
		create_share_link: IDL.Func([FileId, IDL.Nat64], [CreateShareLinkResult], []),
		delete_file: IDL.Func([FileId], [DeleteFileResult], []),
		estimate_upload_cost: IDL.Func([IDL.Nat64, PaymentType], [IDL.Nat64], ['query']),
		garbage_collect: IDL.Func([], [], []),
		get_download_plan: IDL.Func([FileId], [GetDownloadPlanResult], ['query']),
		get_file_meta: IDL.Func([FileId], [GetFileMetaResult], ['query']),
		get_pricing: IDL.Func([], [PricingConfig], ['query']),
		get_status: IDL.Func([], [CanisterStatus], ['query']),
		get_upload_tokens: IDL.Func(
			[IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat32)],
			[GetUploadTokensResult],
			[]
		),
		get_usage: IDL.Func([IDL.Opt(IDL.Principal)], [UserState], ['query']),
		list_files: IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
		provision_bucket: IDL.Func([IDL.Principal], [DeleteFileResult], []),
		reap_expired_uploads: IDL.Func([], [], []),
		remove_file_access: IDL.Func([FileId, IDL.Principal], [DeleteFileResult], []),
		report_chunk_uploaded: IDL.Func([IDL.Vec(IDL.Nat8), IDL.Nat32], [DeleteFileResult], []),
		resolve_share_link: IDL.Func([IDL.Vec(IDL.Nat8)], [GetDownloadPlanResult], ['query']),
		revoke_share_link: IDL.Func([IDL.Vec(IDL.Nat8)], [DeleteFileResult], []),
		start_upload: IDL.Func(
			[IDL.Text, IDL.Text, IDL.Nat64, IDL.Opt(PaymentType)],
			[StartUploadResult],
			[]
		),
		top_up_balance: IDL.Func([IDL.Nat64, PaymentType], [TopUpBalanceResult], [])
	});
};

export const init = ({ IDL }) => {
	const UpgradeArgs = IDL.Record({
		rate_per_gb_per_month: IDL.Opt(IDL.Nat64),
		admins: IDL.Opt(IDL.Vec(IDL.Principal)),
		shared_secret: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const InitArgs = IDL.Record({
		rate_per_gb_per_month: IDL.Nat64,
		admins: IDL.Vec(IDL.Principal),
		shared_secret: IDL.Vec(IDL.Nat8)
	});
	const Args = IDL.Variant({
		Upgrade: IDL.Opt(UpgradeArgs),
		Init: InitArgs
	});

	return [Args];
};
