/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
	owner: Principal;
	subaccount: [] | [Uint8Array];
}
export type AdminSetReadOnlyResult = { Ok: null } | { Err: BucketError };
export type AdminWithdrawResult = { Ok: null } | { Err: BucketError };
export type Args = { Upgrade: [] | [UpgradeArgs] } | { Init: InitArgs };
export type BucketError =
	| { ChunkNotFound: null }
	| { AdminOnly: null }
	| { WrongBucket: null }
	| { PaymentFailed: string }
	| { ChunkNotAllowed: number }
	| { ReadOnly: null }
	| { InvalidSignature: null }
	| { TokenExpired: null }
	| { Unauthorized: null }
	| { Other: string }
	| { InvalidFileId: null };
export interface CallerPaysIcrc2Tokens {
	ledger: Principal;
}
export interface CanisterStatus {
	cycles_balance: bigint;
	memory_usage_bytes: bigint;
	version: string;
	heap_memory_usage_bytes: bigint;
}
export type DeleteFileResult = { Ok: null } | { Err: BucketError };
export interface DownloadToken {
	sig: Uint8Array;
	bucket_id: Principal;
	directory_id: Principal;
	expires_at: bigint;
	file_id: FileId;
}
export interface FileId {
	id: Uint8Array;
	owner: Principal;
}
export type GetChunkResult = { Ok: Uint8Array } | { Err: BucketError };
export interface InitArgs {
	admins: Array<Principal>;
	shared_secret: Uint8Array;
}
export interface PatronPaysIcrc2Tokens {
	ledger: Principal;
	patron: Account;
}
export type PaymentType =
	| { PatronPaysIcrc2Tokens: PatronPaysIcrc2Tokens }
	| { AttachedCycles: null }
	| { CallerPaysIcrc2Cycles: null }
	| { CallerPaysIcrc2Tokens: CallerPaysIcrc2Tokens }
	| { PatronPaysIcrc2Cycles: Account };
export type PutChunkResult = { Ok: number } | { Err: BucketError };
export interface UpgradeArgs {
	admins: [] | [Array<Principal>];
	shared_secret: [] | [Uint8Array];
}
export interface UploadToken {
	sig: Uint8Array;
	bucket_id: Principal;
	upload_id: Uint8Array;
	directory_id: Principal;
	expires_at: bigint;
	allowed_chunks: Uint32Array;
	file_id: FileId;
}
export interface _SERVICE {
	admin_set_read_only: ActorMethod<[boolean], AdminSetReadOnlyResult>;
	admin_withdraw: ActorMethod<[Principal, bigint, Principal], AdminWithdrawResult>;
	delete_file: ActorMethod<[FileId], DeleteFileResult>;
	get_chunk: ActorMethod<[DownloadToken, number], GetChunkResult>;
	get_status: ActorMethod<[], CanisterStatus>;
	put_chunk: ActorMethod<[UploadToken, number, Uint8Array, [] | [PaymentType]], PutChunkResult>;
	stat: ActorMethod<[], string>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
